paths:
    log: "runs"
    raw_data: "./data/train_dataset/sequences"
    train_data: "./data/train_dataset"
params:
        keypoint_extractor: "SIFT"
        # distance in pixel
        keypoint_dist_threshold: 3
        patch_size: 64
        transformation_list: [ 'zoom', 'rotation', 'translation' ]
        predefined_angle_degrees: [ 5, 10, 15 ]
        predefined_zoom_factors: [ 0.9, 0.95, 1.05, 1.1, 1.15 ]
        predefined_translation_pixels: [4, 6, 8, 10]
        model: "Attentinal_GNN"
        nb_epoch: 20
        lr: 5e-5
        batch_size: 1
        minibatch_size: 10
        temperature_parameter: 0.08
        image_size: 128

hydra:
    job:
        chdir: true
